name: .NET

on:
  push:
    branches: 
        - release
  pull_request:
    branches: 
        - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install EF
      run: dotnet tool install --global dotnet-ef
    - name: Build Migration File
      run: dotnet-ef migrations script -i -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/migrate.sql' -s MusicAdventureAPI/MusicAdventureAPI.csproj -p MAData/MAData.csproj
    - name: Azure SQL Deploy (dacpac, file, folder)
      # You may pin to the exact commit or the version.
      # uses: XLipcak/sql-action@1b2b1ea66beb232831e97be2be8382be8f006840
      uses: XLipcak/sql-action@v1.0.5
      with:
        # Name of the Azure SQL Server name, like Fabrikam.database.windows.net.
        server-name: SQL5063.site4now.net
        # The connection string, including authentication information, for the Azure SQL Server database.
        connection-string: '${{ secrets.SQL_CONNECTION_STRING  }}'
        # Path to SQL script file. *.sql or a folder to deploy
        sql-file: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/migrate.sql'
